/**
 * Expo Config Plugin — Health Connect Integration
 * Adds the native pieces react-native-health-connect needs:
 *   - Health Connect permissions + package <queries>
 *   - ACTION_SHOW_PERMISSIONS_RATIONALE on MainActivity
 *   - a dedicated HealthPermissionRationaleActivity (declared in the manifest
 *     AND its Kotlin class generated here, so it survives `expo prebuild --clean`)
 *
 * The generated class is what was missing before: the manifest declared
 * com.seren.app.HealthPermissionRationaleActivity but no class existed, so when
 * Health Connect launched the rationale the app crashed with ClassNotFoundException.
 */
const { withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const RATIONALE_PACKAGE = 'com.seren.app';
const RATIONALE_CLASS = 'HealthPermissionRationaleActivity';

const RATIONALE_KT = `package ${RATIONALE_PACKAGE}

// GENERATED by plugins/withHealthConnect.js — do not edit by hand.
// Shown when the user opens Seren's Health Connect permission rationale.
import android.app.Activity
import android.os.Bundle
import android.view.Gravity
import android.view.ViewGroup
import android.widget.LinearLayout
import android.widget.TextView

class ${RATIONALE_CLASS} : Activity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    val container = LinearLayout(this).apply {
      orientation = LinearLayout.VERTICAL
      gravity = Gravity.CENTER
      setPadding(48, 48, 48, 48)
      layoutParams = LinearLayout.LayoutParams(
        ViewGroup.LayoutParams.MATCH_PARENT,
        ViewGroup.LayoutParams.MATCH_PARENT,
      )
    }
    val title = TextView(this).apply {
      text = "Seren health permissions"
      textSize = 22f
      gravity = Gravity.CENTER
    }
    val body = TextView(this).apply {
      text = "Seren reads Health Connect data such as heart rate, HRV, sleep, steps, " +
        "and oxygen saturation to calculate stress, recovery, and sleep insights on your device."
      textSize = 16f
      gravity = Gravity.CENTER
      setPadding(0, 24, 0, 0)
    }
    container.addView(title)
    container.addView(body)
    setContentView(container)
  }
}
`;

/** Generate the rationale activity's Kotlin class into the android source tree. */
function withRationaleActivityClass(config) {
  return withDangerousMod(config, [
    'android',
    (config) => {
      const pkgDir = path.join(
        config.modRequest.platformProjectRoot,
        'app', 'src', 'main', 'java',
        ...RATIONALE_PACKAGE.split('.'),
      );
      fs.mkdirSync(pkgDir, { recursive: true });
      fs.writeFileSync(path.join(pkgDir, `${RATIONALE_CLASS}.kt`), RATIONALE_KT);
      return config;
    },
  ]);
}

function withHealthConnectManifest(config) {
  return withAndroidManifest(config, (config) => {
    const manifest = config.modResults.manifest;

    // 1. <queries> for the Health Connect package
    if (!manifest['queries']) manifest['queries'] = [];
    manifest['queries'].push({
      package: [{ $: { 'android:name': 'com.google.android.apps.healthdata' } }],
    });

    // 2. ACTION_SHOW_PERMISSIONS_RATIONALE on MainActivity
    const application = manifest.application?.[0];
    if (application?.activity) {
      const mainActivity = application.activity.find(
        (a) => a.$?.['android:name'] === '.MainActivity'
      );
      if (mainActivity) {
        if (!mainActivity['intent-filter']) mainActivity['intent-filter'] = [];
        mainActivity['intent-filter'].push({
          action: [{ $: { 'android:name': 'androidx.health.ACTION_SHOW_PERMISSIONS_RATIONALE' } }],
        });
      }
    }

    // 3. Dedicated rationale activity (class generated by withRationaleActivityClass)
    if (application) {
      if (!application.activity) application.activity = [];
      application.activity.push({
        $: {
          'android:name': `${RATIONALE_PACKAGE}.${RATIONALE_CLASS}`,
          'android:exported': 'true',
        },
        'intent-filter': [
          {
            action: [
              { $: { 'android:name': 'androidx.health.ACTION_SHOW_PERMISSIONS_RATIONALE' } },
            ],
          },
        ],
      });
    }

    return config;
  });
}

function withHealthConnect(config) {
  config = withHealthConnectManifest(config);
  config = withRationaleActivityClass(config);
  return config;
}

module.exports = withHealthConnect;
