/**
 * Expo Config Plugin — Wearable Depression Bridge
 *
 * Generates the two Kotlin files needed to push phone-computed depression
 * risk scores to the paired Wear OS watch via the Wearable Data Layer.
 * Also patches MainApplication.kt to register the ReactPackage.
 *
 * Run automatically by `expo prebuild` (registered in app.json plugins[]).
 */
const { withDangerousMod } = require('@expo/config-plugins');
const fs   = require('fs');
const path = require('path');

const PKG = 'com.seren.app';

// ── WearableDepressionModule.kt ───────────────────────────────────────────────

const MODULE_KT = `package ${PKG}

// GENERATED by plugins/withWearableDepression.js — do not edit by hand.
import android.util.Log
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import com.google.android.gms.wearable.PutDataMapRequest
import com.google.android.gms.wearable.Wearable

/**
 * React Native native module — pushes the phone-computed depression risk
 * to the paired Wear OS watch via the Wearable Data Layer (Data API).
 *
 * The watch listens on the same path in WellnessViewModel.
 */
class WearableDepressionModule(
    private val reactContext: ReactApplicationContext,
) : ReactContextBaseJavaModule(reactContext) {

    companion object {
        private const val TAG  = "SerenDepressionSend"
        const val DATA_PATH    = "/seren/depression"
    }

    override fun getName(): String = "WearableDepressionModule"

    @ReactMethod
    fun sendDepressionToWatch(
        riskScore: Int,
        riskLevel: String,
        probability: Double,
        promise: Promise,
    ) {
        try {
            val request = PutDataMapRequest.create(DATA_PATH).apply {
                dataMap.putInt("riskScore", riskScore)
                dataMap.putString("riskLevel", riskLevel)
                dataMap.putDouble("probability", probability)
                dataMap.putLong("timestamp", System.currentTimeMillis())
            }
            Wearable.getDataClient(reactContext)
                .putDataItem(request.asPutDataRequest().setUrgent())
                .addOnSuccessListener {
                    Log.d(TAG, "Depression data pushed to watch: $riskLevel ($riskScore/100)")
                    promise.resolve(null)
                }
                .addOnFailureListener { e ->
                    Log.w(TAG, "Failed to push depression to watch: \${e.message}")
                    promise.resolve(null)   // non-fatal
                }
        } catch (e: Exception) {
            Log.e(TAG, "sendDepressionToWatch error", e)
            promise.resolve(null)
        }
    }
}
`;

// ── WearableDepressionPackage.kt ─────────────────────────────────────────────

const PACKAGE_KT = `package ${PKG}

// GENERATED by plugins/withWearableDepression.js — do not edit by hand.
import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.uimanager.ViewManager

class WearableDepressionPackage : ReactPackage {
    override fun createNativeModules(ctx: ReactApplicationContext): List<NativeModule> =
        listOf(WearableDepressionModule(ctx))

    override fun createViewManagers(ctx: ReactApplicationContext): List<ViewManager<*, *>> =
        emptyList()
}
`;

// ── Plugin ────────────────────────────────────────────────────────────────────

function withWearableDepression(config) {
  return withDangerousMod(config, [
    'android',
    (config) => {
      const pkgDir = path.join(
        config.modRequest.platformProjectRoot,
        'app', 'src', 'main', 'java',
        ...PKG.split('.'),
      );
      fs.mkdirSync(pkgDir, { recursive: true });

      // Write the two Kotlin files
      fs.writeFileSync(path.join(pkgDir, 'WearableDepressionModule.kt'), MODULE_KT);
      fs.writeFileSync(path.join(pkgDir, 'WearableDepressionPackage.kt'), PACKAGE_KT);

      // Patch MainApplication.kt to register the package
      const mainAppPath = path.join(pkgDir, 'MainApplication.kt');
      if (fs.existsSync(mainAppPath)) {
        let src = fs.readFileSync(mainAppPath, 'utf8');
        // Idempotent: only add if not already present
        if (!src.includes('WearableDepressionPackage')) {
          src = src.replace(
            /PackageList\(this\)\.packages\.apply\s*\{([^}]*)\}/,
            (match, inner) =>
              `PackageList(this).packages.apply {${inner}              add(WearableDepressionPackage())\n            }`,
          );
          fs.writeFileSync(mainAppPath, src, 'utf8');
        }
      }

      return config;
    },
  ]);
}

module.exports = withWearableDepression;
